-- (opcional) Limpeza
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PRODUTO';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PRODUTO_SEQ';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

-- Tabela
CREATE TABLE PRODUTO (
  ID          NUMBER(10)      PRIMARY KEY,
  NOME        VARCHAR2(100)   NOT NULL,
  CATEGORIA   VARCHAR2(50)    NOT NULL,
  PRECO       NUMBER(10,2)    NOT NULL CHECK (PRECO >= 0),
  QUANTIDADE  NUMBER(10)      NOT NULL CHECK (QUANTIDADE >= 0),
  STATUS      VARCHAR2(10)    NOT NULL CHECK (STATUS IN ('ATIVO','INATIVO'))
);

-- Índice auxiliar (opcional)
CREATE INDEX IX_PRODUTO_NOME ON PRODUTO (NOME);
CREATE INDEX IX_PRODUTO_CATEGORIA ON PRODUTO (CATEGORIA);

-- Sequence para ID
CREATE SEQUENCE PRODUTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Dados de exemplo (opcional)
INSERT INTO PRODUTO (ID, NOME, CATEGORIA, PRECO, QUANTIDADE, STATUS)
VALUES (PRODUTO_SEQ.NEXTVAL, 'Teclado', 'Periféricos', 120.00, 10, 'ATIVO');

INSERT INTO PRODUTO (ID, NOME, CATEGORIA, PRECO, QUANTIDADE, STATUS)
VALUES (PRODUTO_SEQ.NEXTVAL, 'Mouse', 'Periféricos', 80.00, 25, 'ATIVO');

COMMIT;
